global:
  scrape_interval: 5s # Intervalo de recolección de métricas

scrape_configs:
  - job_name: 'web'
    static_configs:
      - targets: ['web:80'] # Monitorizar el servidor web

  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysql-exporter:9104'] # Monitorizar el Exporter de MySQL

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Monitorizar Prometheus
